### ISSUE TITLE
.JSON function changes request from GET to POST

### ISSUE THREAD

**Issue by nov1n** [h2non/baloo#12]
In the following code snippet the .JSON function changes the GET request to a POST request.
I found this very confusing, is this expected?

```
var test = baloo.New("http://httpbin.org")
func TestBalooClient(t *testing.T) {
	test.Get("/get").
		JSON(map[string]string{"foo": "bar"}).
		Expect(t).
		Status(200).
		Type("json").
		Done()
}
```

**Comment by h2non** [comment]
That was the expected behavior, but now it's fixed in `gentleman@v1.0.1`.

Try upgrading the package and run your tests again:
```bash
go get -u gopkg.in/h2non/gentleman.v1
```

**Comment by nov1n** [comment]
Thank you.

**Comment by h2non** [comment]
Closing.
