### ISSUE TITLE
failed to Unmarshal: invalid character '\n' in string literal

### ISSUE THREAD

**Issue by dbarrosop** [h2non/baloo#14]
Hello,
when trying to validate the JSON object returned `baloo` will fail if a string contains a newline. For example:

```
func TestATest(t *testing.T) {
	testURL.
		Post("/api/v1/endpoint/").
		Expect(t).
		Status(500).
		Type("json").
		JSON("{}").
		Done()
}
```

Will break with the following error:

```
--- FAIL: TestATest (0.02s)
	expect.go:199: failed to Unmarshal: invalid character '\n' in string literal
FAIL
```
If the JSON blob returned is:

```
{"a_valid_string": "asdadasd\nasdasdasdasd"}
```

**Comment by tomas-fp** [comment]
That's not a valid encoded JSON. Line feed sequences must be escaped within string values.

For more information, see the RFC specification about this:
https://tools.ietf.org/html/rfc7159#section-7

**Comment by dbarrosop** [comment]
Not sure what you mean. It is escaped. In any case here goes some code to proof my point: https://play.golang.org/p/2U02m32lFi

**Comment by h2non** [comment]
That error is produced by `json` stdlib package. The HTTP response body JSON doesn't seem to be a valid one. Verify that your server is returning a valid JSON encoded data.

**Comment by dbarrosop** [comment]
You were right and the marshaling wasn't done properly. Interestingly, a json linter and a schema validators I am using aren't complaining about the response, that's why my first thought was that it was a bug in here.

Thanks and sorry for wasting your time.
