### ISSUE TITLE
assert.JSON: support other JSON values than objects

### ISSUE THREAD

**Issue by dvic** [h2non/baloo#16]
Hi,

I was wondering: do you have a particular reason for having `assert.unmarshalBody()` return `map[string]interface{}`? Of course usually you deal with JSON objects, but JSON has many valid values (http://www.json.org):
- string
- number
- object
- array
- boolean
- `null`

I noticed this restriction because I ran into problems with assert a body using `map[string]string` (which doesn't work, because `assert.compare` assumes `map[string]interface{}` is passed in the assertion. I can imagine that this is too strict and can be relaxed? E.g., checking if the value is a slice, struct, map, or implements `json.Marshaler`? For example, gentleman uses the following logic:

```
                // var data interface{}
		switch data.(type) {
		case string:
			buf.WriteString(data.(string))
		case []byte:
			buf.Write(data.([]byte))
		default:
			if err := json.NewEncoder(buf).Encode(data); err != nil {
				h.Error(ctx, err)
				return
			}
		}
```

Would you accept a PR for this?

**Comment by h2non** [comment]
Yes, it should be an interface without enforcing it as map structure. PR welcome.
