### ISSUE TITLE
Codecoverage

### ISSUE THREAD

**Issue by Allendar** [h2non/baloo#19]
I'm trying to test Baloo to test my project's functionality. It works fine, but when running code coverage like so;

```sh
go test -v -covermode=atomic -coverprofile=coverage.out -run TestBalooSimple
```

I get `coverage: 0.0% of statements`.

Maybe I'm doing it wrong with the command? Or is it running separately and won't work like this? Shouldn't coverage see that while the server is running (in the same code), that the Baloo-visits are actually hitting/covering code?

**Comment by h2non** [comment]
Go native test coverage works differently here. It only analyses at compile time programmatic calls from your tests to your runtime code via AST analysis. 

In other words, this is only valid for unit testing, not for network-based protocol testing (HTTP), like when using `baloo`, which works at a higher level than unit testing.

I don't think there's a way to calculate the test coverage using Go native tools. You should probably look to alternative solutions.

For more information, see: https://blog.golang.org/cover
