### ISSUE TITLE
The error is not accurately describe

### ISSUE THREAD

**Issue by njspok** [h2non/baloo#28]
Very nice library! But there is one drawback.

Run this test
```go
package baloo

import (
	"gopkg.in/h2non/baloo.v3"
	"testing"
)

func Test(t *testing.T) {
	b := baloo.New("http://www.ya.ru")
	_ = b.Get(".").Expect(t).Status(11).Done()
	_ = b.Get(".").Expect(t).Status(11).Done()
	_ = b.Get(".").Expect(t).Status(11).Done()
}
```

Look result
```
=== RUN   Test
--- FAIL: Test (0.35s)
    expect.go:204: Unexpected status code: 404 != 11
    expect.go:204: Unexpected status code: 404 != 11
    expect.go:204: Unexpected status code: 404 != 11
FAIL

Process finished with exit code 1
```

There is no way to know exactly where the test failed. The error message point inside the library

**Comment by zak905** [comment]
I confirm, this is annoying, is there any way to fix this ?

**Comment by zak905** [comment]
Hello any updates about this ? not sure but maybe using `debug.Stack()` https://pkg.go.dev/runtime/debug#Stack could help extracting those info

**Comment by zak905** [comment]
I just submitted a fix https://github.com/h2non/baloo/pull/29
